# Generated by Django 3.2 on 2023-01-14 07:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='filed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('duuid', models.UUIDField(default=uuid.uuid4, verbose_name='文件唯一值')),
                ('name', models.CharField(max_length=100, verbose_name='文件名')),
                ('filedf', models.FileField(upload_to='file/', verbose_name='文件')),
                ('ctime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '文件表',
                'verbose_name_plural': '文件表',
            },
        ),
    ]
